apiVersion: v1
kind: Secret
metadata:
  name: jfrog
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJlb3MuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlpXOXpZV1J0YVc0NlFXUnRhVzR4TWpNPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson